app:
  name: ecommerce
  environment: development
  port: 8000

database:
  host: localhost
  port: 5432
  username: postgres
  password: Jayasree275
  name: nestjs_ecommerce
  synchronize: true

reddis:
  host: localhost
  port: 6379
